.PHONY: help test
help:
	@echo "usage: make <option>"
	@echo "options and effects:"
	@echo "    help                     : Show help"
	@echo "    test                     : Test ..."

test:
	@echo "test ..."
	echo $(conda info --base)

.PHONY: activate
activate:
	@echo "conda activate china-administrative-division"