// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cityFieldNames          = builder.RawFieldNames(&City{})
	cityRows                = strings.Join(cityFieldNames, ",")
	cityRowsExpectAutoSet   = strings.Join(stringx.Remove(cityFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	cityRowsWithPlaceHolder = strings.Join(stringx.Remove(cityFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	cityModel interface {
		Insert(ctx context.Context, data *City) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*City, error)
		Update(ctx context.Context, data *City) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCityModel struct {
		conn  sqlx.SqlConn
		table string
	}

	City struct {
		Id            int64     `db:"id"`
		Name          string    `db:"name"`            // 城市名称
		Code          string    `db:"code"`            // 统计用区划代码
		ProvinceId    int64     `db:"province_id"`     // province表id字段
		Url           string    `db:"url"`             // 被抓取的url
		ChildUrl      string    `db:"child_url"`       // 指向的子url
		Creator       string    `db:"creator"`         // 创建者
		Updater       string    `db:"updater"`         // 更新者
		CreatedAt     time.Time `db:"created_at"`      // 创建时间
		UpdatedAt     time.Time `db:"updated_at"`      // 更新时间
		DataUpdatedAt time.Time `db:"data_updated_at"` // 更新时间
	}
)

func newCityModel(conn sqlx.SqlConn) *defaultCityModel {
	return &defaultCityModel{
		conn:  conn,
		table: "`city`",
	}
}

func (m *defaultCityModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCityModel) FindOne(ctx context.Context, id int64) (*City, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cityRows, m.table)
	var resp City
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCityModel) Insert(ctx context.Context, data *City) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, cityRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Code, data.ProvinceId, data.Url, data.ChildUrl, data.Creator, data.Updater, data.DataUpdatedAt)
	return ret, err
}

func (m *defaultCityModel) Update(ctx context.Context, data *City) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cityRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Code, data.ProvinceId, data.Url, data.ChildUrl, data.Creator, data.Updater, data.DataUpdatedAt, data.Id)
	return err
}

func (m *defaultCityModel) tableName() string {
	return m.table
}
