// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	countyFieldNames          = builder.RawFieldNames(&County{})
	countyRows                = strings.Join(countyFieldNames, ",")
	countyRowsExpectAutoSet   = strings.Join(stringx.Remove(countyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	countyRowsWithPlaceHolder = strings.Join(stringx.Remove(countyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	countyModel interface {
		Insert(ctx context.Context, data *County) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*County, error)
		Update(ctx context.Context, data *County) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCountyModel struct {
		conn  sqlx.SqlConn
		table string
	}

	County struct {
		Id            int64     `db:"id"`
		Name          string    `db:"name"`            // 县名称
		Code          string    `db:"code"`            // 统计用区划代码
		ProvinceId    int64     `db:"province_id"`     // province表id字段
		CityId        int64     `db:"city_id"`         // city表id字段
		Url           string    `db:"url"`             // 被抓取的url
		ChildUrl      string    `db:"child_url"`       // 指向的子url
		Creator       string    `db:"creator"`         // 创建者
		Updater       string    `db:"updater"`         // 更新者
		CreatedAt     time.Time `db:"created_at"`      // 创建时间
		UpdatedAt     time.Time `db:"updated_at"`      // 更新时间
		DataUpdatedAt time.Time `db:"data_updated_at"` // 数据更新时间
	}
)

func newCountyModel(conn sqlx.SqlConn) *defaultCountyModel {
	return &defaultCountyModel{
		conn:  conn,
		table: "`county`",
	}
}

func (m *defaultCountyModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCountyModel) FindOne(ctx context.Context, id int64) (*County, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", countyRows, m.table)
	var resp County
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCountyModel) Insert(ctx context.Context, data *County) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, countyRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Code, data.ProvinceId, data.CityId, data.Url, data.ChildUrl, data.Creator, data.Updater, data.DataUpdatedAt)
	return ret, err
}

func (m *defaultCountyModel) Update(ctx context.Context, data *County) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, countyRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Code, data.ProvinceId, data.CityId, data.Url, data.ChildUrl, data.Creator, data.Updater, data.DataUpdatedAt, data.Id)
	return err
}

func (m *defaultCountyModel) tableName() string {
	return m.table
}
