// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	provinceFieldNames          = builder.RawFieldNames(&Province{})
	provinceRows                = strings.Join(provinceFieldNames, ",")
	provinceRowsExpectAutoSet   = strings.Join(stringx.Remove(provinceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	provinceRowsWithPlaceHolder = strings.Join(stringx.Remove(provinceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	provinceModel interface {
		Insert(ctx context.Context, data *Province) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Province, error)
		Update(ctx context.Context, data *Province) error
		Delete(ctx context.Context, id int64) error
	}

	defaultProvinceModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Province struct {
		Id             int64     `db:"id"`
		Name           string    `db:"name"`            // 省名称
		Code           string    `db:"code"`            // 统计用区划代码
		Url            string    `db:"url"`             // 被抓取的url
		ChildUrl       string    `db:"child_url"`       // 指向的子url
		IsMunicipality int64     `db:"is_municipality"` // 是不是直辖市:1-是;0-否
		Creator        string    `db:"creator"`         // 创建者
		Updater        string    `db:"updater"`         // 更新者
		CreatedAt      time.Time `db:"created_at"`      // 创建时间
		UpdatedAt      time.Time `db:"updated_at"`      // 更新时间
		DataUpdatedAt  time.Time `db:"data_updated_at"` // 数据更新时间
	}
)

func newProvinceModel(conn sqlx.SqlConn) *defaultProvinceModel {
	return &defaultProvinceModel{
		conn:  conn,
		table: "`province`",
	}
}

func (m *defaultProvinceModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProvinceModel) FindOne(ctx context.Context, id int64) (*Province, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", provinceRows, m.table)
	var resp Province
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProvinceModel) Insert(ctx context.Context, data *Province) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, provinceRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Code, data.Url, data.ChildUrl, data.IsMunicipality, data.Creator, data.Updater, data.DataUpdatedAt)
	return ret, err
}

func (m *defaultProvinceModel) Update(ctx context.Context, data *Province) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, provinceRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Code, data.Url, data.ChildUrl, data.IsMunicipality, data.Creator, data.Updater, data.DataUpdatedAt, data.Id)
	return err
}

func (m *defaultProvinceModel) tableName() string {
	return m.table
}
