// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProvince = "province"

// Province 省份表
type Province struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name           string    `gorm:"column:name;not null;comment:省名称" json:"name"`                                                    // 省名称
	Code           string    `gorm:"column:code;not null;comment:统计用区划代码" json:"code"`                                                // 统计用区划代码
	URL            string    `gorm:"column:url;not null;comment:被抓取的url" json:"url"`                                                  // 被抓取的url
	ChildURL       string    `gorm:"column:child_url;not null;comment:指向的子url" json:"child_url"`                                      // 指向的子url
	IsMunicipality int32     `gorm:"column:is_municipality;not null;comment:是不是直辖市:1-是;0-否" json:"is_municipality"`                   // 是不是直辖市:1-是;0-否
	Creator        string    `gorm:"column:creator;not null;comment:创建者" json:"creator"`                                              // 创建者
	Updater        string    `gorm:"column:updater;not null;comment:更新者" json:"updater"`                                              // 更新者
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`             // 创建时间
	UpdatedAt      time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`             // 更新时间
	DataUpdatedAt  time.Time `gorm:"column:data_updated_at;not null;default:CURRENT_TIMESTAMP;comment:数据更新时间" json:"data_updated_at"` // 数据更新时间
}

// TableName Province's table name
func (*Province) TableName() string {
	return TableNameProvince
}
