// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVillage = "village"

// Village 村庄表
type Village struct {
	ID            int64      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Name          string     `gorm:"column:name;type:varchar(50);not null;comment:村庄名称" json:"name"`                                                 // 村庄名称
	Code          string     `gorm:"column:code;type:varchar(20);not null;comment:统计用区划代码" json:"code"`                                              // 统计用区划代码
	ClassifyCode  string     `gorm:"column:classify_code;type:varchar(10);not null;comment:城乡分类码" json:"classify_code"`                              // 城乡分类码
	ProvinceID    int64      `gorm:"column:province_id;type:int;not null;comment:province表id字段" json:"province_id"`                                  // province表id字段
	CityID        int64      `gorm:"column:city_id;type:int;not null;comment:city表id字段" json:"city_id"`                                              // city表id字段
	CountyID      int64      `gorm:"column:county_id;type:int;not null;comment:county表id字段" json:"county_id"`                                        // county表id字段
	TownID        int64      `gorm:"column:town_id;type:int;not null;comment:town表id字段" json:"town_id"`                                              // town表id字段
	URL           string     `gorm:"column:url;type:varchar(200);not null;comment:被抓取的url" json:"url"`                                               // 被抓取的url
	Creator       string     `gorm:"column:creator;type:varchar(32);not null;comment:创建者" json:"creator"`                                            // 创建者
	Updater       string     `gorm:"column:updater;type:varchar(32);not null;comment:更新者" json:"updater"`                                            // 更新者
	CreatedAt     *time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`             // 创建时间
	UpdatedAt     *time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`             // 更新时间
	DataUpdatedAt *time.Time `gorm:"column:data_updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:数据更新时间" json:"data_updated_at"` // 数据更新时间
}

// TableName Village's table name
func (*Village) TableName() string {
	return TableNameVillage
}
