// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"alice/dao/model"
)

func newVillage(db *gorm.DB, opts ...gen.DOOption) village {
	_village := village{}

	_village.villageDo.UseDB(db, opts...)
	_village.villageDo.UseModel(&model.Village{})

	tableName := _village.villageDo.TableName()
	_village.ALL = field.NewAsterisk(tableName)
	_village.ID = field.NewInt64(tableName, "id")
	_village.Name = field.NewString(tableName, "name")
	_village.Code = field.NewString(tableName, "code")
	_village.ClassifyCode = field.NewString(tableName, "classify_code")
	_village.ProvinceID = field.NewInt64(tableName, "province_id")
	_village.CityID = field.NewInt64(tableName, "city_id")
	_village.CountyID = field.NewInt64(tableName, "county_id")
	_village.TownID = field.NewInt64(tableName, "town_id")
	_village.URL = field.NewString(tableName, "url")
	_village.Creator = field.NewString(tableName, "creator")
	_village.Updater = field.NewString(tableName, "updater")
	_village.CreatedAt = field.NewTime(tableName, "created_at")
	_village.UpdatedAt = field.NewTime(tableName, "updated_at")
	_village.DataUpdatedAt = field.NewTime(tableName, "data_updated_at")

	_village.fillFieldMap()

	return _village
}

// village 村庄表
type village struct {
	villageDo

	ALL           field.Asterisk
	ID            field.Int64
	Name          field.String // 村庄名称
	Code          field.String // 统计用区划代码
	ClassifyCode  field.String // 城乡分类码
	ProvinceID    field.Int64  // province表id字段
	CityID        field.Int64  // city表id字段
	CountyID      field.Int64  // county表id字段
	TownID        field.Int64  // town表id字段
	URL           field.String // 被抓取的url
	Creator       field.String // 创建者
	Updater       field.String // 更新者
	CreatedAt     field.Time   // 创建时间
	UpdatedAt     field.Time   // 更新时间
	DataUpdatedAt field.Time   // 数据更新时间

	fieldMap map[string]field.Expr
}

func (v village) Table(newTableName string) *village {
	v.villageDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v village) As(alias string) *village {
	v.villageDo.DO = *(v.villageDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *village) updateTableName(table string) *village {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt64(table, "id")
	v.Name = field.NewString(table, "name")
	v.Code = field.NewString(table, "code")
	v.ClassifyCode = field.NewString(table, "classify_code")
	v.ProvinceID = field.NewInt64(table, "province_id")
	v.CityID = field.NewInt64(table, "city_id")
	v.CountyID = field.NewInt64(table, "county_id")
	v.TownID = field.NewInt64(table, "town_id")
	v.URL = field.NewString(table, "url")
	v.Creator = field.NewString(table, "creator")
	v.Updater = field.NewString(table, "updater")
	v.CreatedAt = field.NewTime(table, "created_at")
	v.UpdatedAt = field.NewTime(table, "updated_at")
	v.DataUpdatedAt = field.NewTime(table, "data_updated_at")

	v.fillFieldMap()

	return v
}

func (v *village) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *village) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 14)
	v.fieldMap["id"] = v.ID
	v.fieldMap["name"] = v.Name
	v.fieldMap["code"] = v.Code
	v.fieldMap["classify_code"] = v.ClassifyCode
	v.fieldMap["province_id"] = v.ProvinceID
	v.fieldMap["city_id"] = v.CityID
	v.fieldMap["county_id"] = v.CountyID
	v.fieldMap["town_id"] = v.TownID
	v.fieldMap["url"] = v.URL
	v.fieldMap["creator"] = v.Creator
	v.fieldMap["updater"] = v.Updater
	v.fieldMap["created_at"] = v.CreatedAt
	v.fieldMap["updated_at"] = v.UpdatedAt
	v.fieldMap["data_updated_at"] = v.DataUpdatedAt
}

func (v village) clone(db *gorm.DB) village {
	v.villageDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v village) replaceDB(db *gorm.DB) village {
	v.villageDo.ReplaceDB(db)
	return v
}

type villageDo struct{ gen.DO }

type IVillageDo interface {
	gen.SubQuery
	Debug() IVillageDo
	WithContext(ctx context.Context) IVillageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IVillageDo
	WriteDB() IVillageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IVillageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IVillageDo
	Not(conds ...gen.Condition) IVillageDo
	Or(conds ...gen.Condition) IVillageDo
	Select(conds ...field.Expr) IVillageDo
	Where(conds ...gen.Condition) IVillageDo
	Order(conds ...field.Expr) IVillageDo
	Distinct(cols ...field.Expr) IVillageDo
	Omit(cols ...field.Expr) IVillageDo
	Join(table schema.Tabler, on ...field.Expr) IVillageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IVillageDo
	RightJoin(table schema.Tabler, on ...field.Expr) IVillageDo
	Group(cols ...field.Expr) IVillageDo
	Having(conds ...gen.Condition) IVillageDo
	Limit(limit int) IVillageDo
	Offset(offset int) IVillageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IVillageDo
	Unscoped() IVillageDo
	Create(values ...*model.Village) error
	CreateInBatches(values []*model.Village, batchSize int) error
	Save(values ...*model.Village) error
	First() (*model.Village, error)
	Take() (*model.Village, error)
	Last() (*model.Village, error)
	Find() ([]*model.Village, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Village, err error)
	FindInBatches(result *[]*model.Village, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Village) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IVillageDo
	Assign(attrs ...field.AssignExpr) IVillageDo
	Joins(fields ...field.RelationField) IVillageDo
	Preload(fields ...field.RelationField) IVillageDo
	FirstOrInit() (*model.Village, error)
	FirstOrCreate() (*model.Village, error)
	FindByPage(offset int, limit int) (result []*model.Village, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IVillageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v villageDo) Debug() IVillageDo {
	return v.withDO(v.DO.Debug())
}

func (v villageDo) WithContext(ctx context.Context) IVillageDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v villageDo) ReadDB() IVillageDo {
	return v.Clauses(dbresolver.Read)
}

func (v villageDo) WriteDB() IVillageDo {
	return v.Clauses(dbresolver.Write)
}

func (v villageDo) Session(config *gorm.Session) IVillageDo {
	return v.withDO(v.DO.Session(config))
}

func (v villageDo) Clauses(conds ...clause.Expression) IVillageDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v villageDo) Returning(value interface{}, columns ...string) IVillageDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v villageDo) Not(conds ...gen.Condition) IVillageDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v villageDo) Or(conds ...gen.Condition) IVillageDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v villageDo) Select(conds ...field.Expr) IVillageDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v villageDo) Where(conds ...gen.Condition) IVillageDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v villageDo) Order(conds ...field.Expr) IVillageDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v villageDo) Distinct(cols ...field.Expr) IVillageDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v villageDo) Omit(cols ...field.Expr) IVillageDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v villageDo) Join(table schema.Tabler, on ...field.Expr) IVillageDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v villageDo) LeftJoin(table schema.Tabler, on ...field.Expr) IVillageDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v villageDo) RightJoin(table schema.Tabler, on ...field.Expr) IVillageDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v villageDo) Group(cols ...field.Expr) IVillageDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v villageDo) Having(conds ...gen.Condition) IVillageDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v villageDo) Limit(limit int) IVillageDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v villageDo) Offset(offset int) IVillageDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v villageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IVillageDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v villageDo) Unscoped() IVillageDo {
	return v.withDO(v.DO.Unscoped())
}

func (v villageDo) Create(values ...*model.Village) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v villageDo) CreateInBatches(values []*model.Village, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v villageDo) Save(values ...*model.Village) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v villageDo) First() (*model.Village, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Village), nil
	}
}

func (v villageDo) Take() (*model.Village, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Village), nil
	}
}

func (v villageDo) Last() (*model.Village, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Village), nil
	}
}

func (v villageDo) Find() ([]*model.Village, error) {
	result, err := v.DO.Find()
	return result.([]*model.Village), err
}

func (v villageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Village, err error) {
	buf := make([]*model.Village, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v villageDo) FindInBatches(result *[]*model.Village, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v villageDo) Attrs(attrs ...field.AssignExpr) IVillageDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v villageDo) Assign(attrs ...field.AssignExpr) IVillageDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v villageDo) Joins(fields ...field.RelationField) IVillageDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v villageDo) Preload(fields ...field.RelationField) IVillageDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v villageDo) FirstOrInit() (*model.Village, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Village), nil
	}
}

func (v villageDo) FirstOrCreate() (*model.Village, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Village), nil
	}
}

func (v villageDo) FindByPage(offset int, limit int) (result []*model.Village, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v villageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v villageDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v villageDo) Delete(models ...*model.Village) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *villageDo) withDO(do gen.Dao) *villageDo {
	v.DO = *do.(*gen.DO)
	return v
}
