.PHONY: help test
help:
	@echo "usage: make <option>"
	@echo "options and effects:"
	@echo "    help                     : Show help"
	@echo "    test                     : Test ..."

test:
	@echo "test ..."
	echo $(conda info --base)

.PHONY: export

.PHONY: export
export:
	@python export.py