// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	city "alice/internal/handler/city"
	county "alice/internal/handler/county"
	province "alice/internal/handler/province"
	"alice/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: province.ListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/province"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: city.ListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/city"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: county.ListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/county"),
	)
}
